services:
  - type: web
    name: asistencia-universitaria
    runtime: node
    plan: free
    buildCommand: npm install --build-from-source
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
